import Head from 'next/head'
import Spline from '@splinetool/react-spline';
import Image from 'next/image'
import Footer from '../../components/footer'
import Header from '../../components/header'
import SubBanner from '../../components/subbanner';
import styles from '@/styles/Home.module.css'


export default function Home() {
  return (
    <>
      <Head>
        <title>Assessment 2</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/Asset 2.svg" />
      </Head>
      <Header></Header>

      <main className={styles.main}>
        <div className={styles.container}>
      <Spline scene="https://prod.spline.design/W2CewIaawdwNRiY5/scene.splinecode"/>
      <div className={styles.splineinfo}>
      <h2>Discover, Connect, and Experience Music Like Never Before with our Innovative Music App</h2>
      <button>See More</button>
      </div>
      </div>
      <SubBanner/>
      </main>
    
      <Footer/>
    </>
  )
}
